name: verifio-local

services:
  verifio-postgres:
    image: postgres:17-alpine
    container_name: verifio-postgres
    volumes:
      - ../docker-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: verifio
      POSTGRES_USER: verifio
      POSTGRES_PASSWORD: verifio123
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      test: [ "CMD", "pg_isready", "-U", "verifio", "-d", "verifio" ]
    restart: unless-stopped

  verifio-redis:
    image: redis:7-alpine
    container_name: verifio-redis
    command: redis-server --requirepass verifio123
    volumes:
      - ../docker-data/redis:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  verifio-proxy:
    image: caddy:2-alpine
    container_name: verifio-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../docker-data/caddy:/data
      - ../docker-data/caddy:/config
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
